// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace wwi.bl.EF
{
    public partial class City
    {
        public City()
        {
            CustomerDeliveryCities = new HashSet<Customer>();
            CustomerPostalCities = new HashSet<Customer>();
            SupplierDeliveryCities = new HashSet<Supplier>();
            SupplierPostalCities = new HashSet<Supplier>();
            SystemParameterDeliveryCities = new HashSet<SystemParameter>();
            SystemParameterPostalCities = new HashSet<SystemParameter>();
        }

        public int CityID { get; set; }
        public string CityName { get; set; }
        public int StateProvinceID { get; set; }
        public long? LatestRecordedPopulation { get; set; }
        public int LastEditedBy { get; set; }

        public virtual Person LastEditedByNavigation { get; set; }
        public virtual StateProvince StateProvince { get; set; }
        public virtual ICollection<Customer> CustomerDeliveryCities { get; set; }
        public virtual ICollection<Customer> CustomerPostalCities { get; set; }
        public virtual ICollection<Supplier> SupplierDeliveryCities { get; set; }
        public virtual ICollection<Supplier> SupplierPostalCities { get; set; }
        public virtual ICollection<SystemParameter> SystemParameterDeliveryCities { get; set; }
        public virtual ICollection<SystemParameter> SystemParameterPostalCities { get; set; }
    }
}