// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace wwi.hr.EF
{
    public partial class Configuration_ApplyColumnstoreIndexingResult
    {
    }
}
