// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace wwi.hr.EF
{
    public partial class People
    {
        public People()
        {
            BuyingGroups = new HashSet<BuyingGroup>();
            Cities = new HashSet<City>();
            Colors = new HashSet<Color>();
            Countries = new HashSet<Country>();
            CustomerAlternateContactPersons = new HashSet<Customer>();
            CustomerCategories = new HashSet<CustomerCategory>();
            CustomerLastEditedByNavigations = new HashSet<Customer>();
            CustomerPrimaryContactPersons = new HashSet<Customer>();
            CustomerTransactions = new HashSet<CustomerTransaction>();
            DeliveryMethods = new HashSet<DeliveryMethod>();
            InverseLastEditedByNavigation = new HashSet<People>();
            InvoiceAccountsPersons = new HashSet<Invoice>();
            InvoiceContactPersons = new HashSet<Invoice>();
            InvoiceLastEditedByNavigations = new HashSet<Invoice>();
            InvoiceLines = new HashSet<InvoiceLine>();
            InvoicePackedByPersons = new HashSet<Invoice>();
            InvoiceSalespersonPersons = new HashSet<Invoice>();
            OrderContactPersons = new HashSet<Order>();
            OrderLastEditedByNavigations = new HashSet<Order>();
            OrderLines = new HashSet<OrderLine>();
            OrderPickedByPersons = new HashSet<Order>();
            OrderSalespersonPersons = new HashSet<Order>();
            PackageTypes = new HashSet<PackageType>();
            PaymentMethods = new HashSet<PaymentMethod>();
            PurchaseOrderContactPersons = new HashSet<PurchaseOrder>();
            PurchaseOrderLastEditedByNavigations = new HashSet<PurchaseOrder>();
            PurchaseOrderLines = new HashSet<PurchaseOrderLine>();
            SpecialDeals = new HashSet<SpecialDeal>();
            StateProvinces = new HashSet<StateProvince>();
            StockGroups = new HashSet<StockGroup>();
            StockItemHoldings = new HashSet<StockItemHolding>();
            StockItemStockGroups = new HashSet<StockItemStockGroup>();
            StockItemTransactions = new HashSet<StockItemTransaction>();
            StockItems = new HashSet<StockItem>();
            SupplierAlternateContactPersons = new HashSet<Supplier>();
            SupplierCategories = new HashSet<SupplierCategory>();
            SupplierLastEditedByNavigations = new HashSet<Supplier>();
            SupplierPrimaryContactPersons = new HashSet<Supplier>();
            SupplierTransactions = new HashSet<SupplierTransaction>();
            SystemParameters = new HashSet<SystemParameter>();
            TransactionTypes = new HashSet<TransactionType>();
        }

        public int PersonId { get; set; }
        public string FullName { get; set; }
        public string PreferredName { get; set; }
        public string SearchName { get; set; }
        public bool IsPermittedToLogon { get; set; }
        public string LogonName { get; set; }
        public bool IsExternalLogonProvider { get; set; }
        public byte[] HashedPassword { get; set; }
        public bool IsSystemUser { get; set; }
        public bool IsEmployee { get; set; }
        public bool IsSalesperson { get; set; }
        public string UserPreferences { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string EmailAddress { get; set; }
        public byte[] Photo { get; set; }
        public string CustomFields { get; set; }
        public string OtherLanguages { get; set; }
        public int LastEditedBy { get; set; }
        public DateTime ValidFrom { get; set; }
        public DateTime ValidTo { get; set; }

        public virtual People LastEditedByNavigation { get; set; }
        public virtual ICollection<BuyingGroup> BuyingGroups { get; set; }
        public virtual ICollection<City> Cities { get; set; }
        public virtual ICollection<Color> Colors { get; set; }
        public virtual ICollection<Country> Countries { get; set; }
        public virtual ICollection<Customer> CustomerAlternateContactPersons { get; set; }
        public virtual ICollection<CustomerCategory> CustomerCategories { get; set; }
        public virtual ICollection<Customer> CustomerLastEditedByNavigations { get; set; }
        public virtual ICollection<Customer> CustomerPrimaryContactPersons { get; set; }
        public virtual ICollection<CustomerTransaction> CustomerTransactions { get; set; }
        public virtual ICollection<DeliveryMethod> DeliveryMethods { get; set; }
        public virtual ICollection<People> InverseLastEditedByNavigation { get; set; }
        public virtual ICollection<Invoice> InvoiceAccountsPersons { get; set; }
        public virtual ICollection<Invoice> InvoiceContactPersons { get; set; }
        public virtual ICollection<Invoice> InvoiceLastEditedByNavigations { get; set; }
        public virtual ICollection<InvoiceLine> InvoiceLines { get; set; }
        public virtual ICollection<Invoice> InvoicePackedByPersons { get; set; }
        public virtual ICollection<Invoice> InvoiceSalespersonPersons { get; set; }
        public virtual ICollection<Order> OrderContactPersons { get; set; }
        public virtual ICollection<Order> OrderLastEditedByNavigations { get; set; }
        public virtual ICollection<OrderLine> OrderLines { get; set; }
        public virtual ICollection<Order> OrderPickedByPersons { get; set; }
        public virtual ICollection<Order> OrderSalespersonPersons { get; set; }
        public virtual ICollection<PackageType> PackageTypes { get; set; }
        public virtual ICollection<PaymentMethod> PaymentMethods { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrderContactPersons { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrderLastEditedByNavigations { get; set; }
        public virtual ICollection<PurchaseOrderLine> PurchaseOrderLines { get; set; }
        public virtual ICollection<SpecialDeal> SpecialDeals { get; set; }
        public virtual ICollection<StateProvince> StateProvinces { get; set; }
        public virtual ICollection<StockGroup> StockGroups { get; set; }
        public virtual ICollection<StockItemHolding> StockItemHoldings { get; set; }
        public virtual ICollection<StockItemStockGroup> StockItemStockGroups { get; set; }
        public virtual ICollection<StockItemTransaction> StockItemTransactions { get; set; }
        public virtual ICollection<StockItem> StockItems { get; set; }
        public virtual ICollection<Supplier> SupplierAlternateContactPersons { get; set; }
        public virtual ICollection<SupplierCategory> SupplierCategories { get; set; }
        public virtual ICollection<Supplier> SupplierLastEditedByNavigations { get; set; }
        public virtual ICollection<Supplier> SupplierPrimaryContactPersons { get; set; }
        public virtual ICollection<SupplierTransaction> SupplierTransactions { get; set; }
        public virtual ICollection<SystemParameter> SystemParameters { get; set; }
        public virtual ICollection<TransactionType> TransactionTypes { get; set; }
    }
}