// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace wwi.bl.EF
{
    public partial class GetPurchaseUpdatesResult
    {
        [Column("Date Key")]
        public DateTime? DateKey { get; set; }
        [Column("WWI Purchase Order ID")]
        public int WWIPurchaseOrderID { get; set; }
        [Column("Ordered Outers")]
        public int OrderedOuters { get; set; }
        [Column("Ordered Quantity")]
        public int? OrderedQuantity { get; set; }
        [Column("Received Outers")]
        public int ReceivedOuters { get; set; }
        public string Package { get; set; }
        [Column("Is Order Finalized")]
        public bool IsOrderFinalized { get; set; }
        [Column("WWI Supplier ID")]
        public int WWISupplierID { get; set; }
        [Column("WWI Stock Item ID")]
        public int WWIStockItemID { get; set; }
        [Column("Last Modified When")]
        public DateTime LastModifiedWhen { get; set; }
    }
}
