// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace wwi.bl.EF
{
    public partial class GetSaleUpdatesResult
    {
        [Column("Invoice Date Key")]
        public DateTime? InvoiceDateKey { get; set; }
        [Column("Delivery Date Key")]
        public DateTime? DeliveryDateKey { get; set; }
        [Column("WWI Invoice ID")]
        public int WWIInvoiceID { get; set; }
        public string Description { get; set; }
        public string Package { get; set; }
        public int Quantity { get; set; }
        [Column("Unit Price")]
        public decimal? UnitPrice { get; set; }
        [Column("Tax Rate")]
        public decimal TaxRate { get; set; }
        [Column("Total Excluding Tax")]
        public decimal? TotalExcludingTax { get; set; }
        [Column("Tax Amount")]
        public decimal TaxAmount { get; set; }
        public decimal Profit { get; set; }
        [Column("Total Including Tax")]
        public decimal TotalIncludingTax { get; set; }
        [Column("Total Dry Items")]
        public int TotalDryItems { get; set; }
        [Column("Total Chiller Items")]
        public int TotalChillerItems { get; set; }
        [Column("WWI City ID")]
        public int WWICityID { get; set; }
        [Column("WWI Customer ID")]
        public int WWICustomerID { get; set; }
        [Column("WWI Bill To Customer ID")]
        public int WWIBillToCustomerID { get; set; }
        [Column("WWI Stock Item ID")]
        public int WWIStockItemID { get; set; }
        [Column("WWI Saleperson ID")]
        public int WWISalepersonID { get; set; }
        [Column("Last Modified When")]
        public DateTime LastModifiedWhen { get; set; }
    }
}
