// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace wwi.hr.EF
{
    public partial class GetTransactionUpdatesResult
    {
        [Column("Date Key")]
        public DateTime? DateKey { get; set; }
        [Column("WWI Customer Transaction ID")]
        public int? WWICustomerTransactionID { get; set; }
        [Column("WWI Supplier Transaction ID")]
        public int? WWISupplierTransactionID { get; set; }
        [Column("WWI Invoice ID")]
        public int? WWIInvoiceID { get; set; }
        [Column("WWI Purchase Order ID")]
        public int? WWIPurchaseOrderID { get; set; }
        [Column("Supplier Invoice Number")]
        public string SupplierInvoiceNumber { get; set; }
        [Column("Total Excluding Tax")]
        public decimal TotalExcludingTax { get; set; }
        [Column("Tax Amount")]
        public decimal TaxAmount { get; set; }
        [Column("Total Including Tax")]
        public decimal TotalIncludingTax { get; set; }
        [Column("Outstanding Balance")]
        public decimal OutstandingBalance { get; set; }
        [Column("Is Finalized")]
        public bool? IsFinalized { get; set; }
        [Column("WWI Customer ID")]
        public int? WWICustomerID { get; set; }
        [Column("WWI Bill To Customer ID")]
        public int? WWIBillToCustomerID { get; set; }
        [Column("WWI Supplier ID")]
        public int? WWISupplierID { get; set; }
        [Column("WWI Transaction Type ID")]
        public int WWITransactionTypeID { get; set; }
        [Column("WWI Payment Method ID")]
        public int? WWIPaymentMethodID { get; set; }
        [Column("Last Modified When")]
        public DateTime LastModifiedWhen { get; set; }
    }
}
