// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using chores.bl.ef.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
#nullable disable

namespace chores.bl.ef
{
    public partial class ChoresDbContext : DbContext
    {
        public ChoresDbContext()
        {
        }

        public ChoresDbContext(DbContextOptions<ChoresDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Chore> Chores { get; set; }
        public virtual DbSet<CompletedChore> CompletedChores { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Configurations.ChoreConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.CompletedChoreConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            var config = new ConfigurationBuilder()
                .AddJsonFile("config.json", optional: false).Build(); // TODO - should be part of configuration root

            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlite(config.GetConnectionString("chores"));
            }
        }
    }
}
