// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace chores.bl.ef
{
    public partial class CompletedChore
    {
        public long Id { get; set; }
        public long ChoreId { get; set; }
        public long UserId { get; set; }
        public long Date { get; set; }

        public virtual Chore Chore { get; set; }
    }
}