// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using wwi.hr.EF;


namespace wwi.hr.EF.Configurations
{
    public partial class ColdRoomTemperatureConfiguration : IEntityTypeConfiguration<ColdRoomTemperature>
    {
        public void Configure(EntityTypeBuilder<ColdRoomTemperature> entity)
        {
            entity.HasKey(e => e.ColdRoomTemperatureId)
                .HasName("PK_Warehouse_ColdRoomTemperatures")
                .IsClustered(false);

            entity.ToTable("ColdRoomTemperatures", "Warehouse");

            entity.HasAnnotation("SqlServer:MemoryOptimized", true);

            entity.HasIndex(e => e.ColdRoomSensorNumber, "IX_Warehouse_ColdRoomTemperatures_ColdRoomSensorNumber");

            entity.Property(e => e.ColdRoomTemperatureId).HasColumnName("ColdRoomTemperatureID");

            entity.Property(e => e.Temperature).HasColumnType("decimal(10, 2)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ColdRoomTemperature> entity);
    }
}
