// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using wwi.hr.EF;


namespace wwi.hr.EF.Configurations
{
    public partial class SpecialDealConfiguration : IEntityTypeConfiguration<SpecialDeal>
    {
        public void Configure(EntityTypeBuilder<SpecialDeal> entity)
        {
            entity.ToTable("SpecialDeals", "Sales");

            entity.HasIndex(e => e.BuyingGroupId, "FK_Sales_SpecialDeals_BuyingGroupID");

            entity.HasIndex(e => e.CustomerCategoryId, "FK_Sales_SpecialDeals_CustomerCategoryID");

            entity.HasIndex(e => e.CustomerId, "FK_Sales_SpecialDeals_CustomerID");

            entity.HasIndex(e => e.StockGroupId, "FK_Sales_SpecialDeals_StockGroupID");

            entity.HasIndex(e => e.StockItemId, "FK_Sales_SpecialDeals_StockItemID");

            entity.Property(e => e.SpecialDealId)
                .HasColumnName("SpecialDealID")
                .HasDefaultValueSql("(NEXT VALUE FOR [Sequences].[SpecialDealID])");

            entity.Property(e => e.BuyingGroupId).HasColumnName("BuyingGroupID");

            entity.Property(e => e.CustomerCategoryId).HasColumnName("CustomerCategoryID");

            entity.Property(e => e.CustomerId).HasColumnName("CustomerID");

            entity.Property(e => e.DealDescription)
                .IsRequired()
                .HasMaxLength(30);

            entity.Property(e => e.DiscountAmount).HasColumnType("decimal(18, 2)");

            entity.Property(e => e.DiscountPercentage).HasColumnType("decimal(18, 3)");

            entity.Property(e => e.EndDate).HasColumnType("date");

            entity.Property(e => e.LastEditedWhen).HasDefaultValueSql("(sysdatetime())");

            entity.Property(e => e.StartDate).HasColumnType("date");

            entity.Property(e => e.StockGroupId).HasColumnName("StockGroupID");

            entity.Property(e => e.StockItemId).HasColumnName("StockItemID");

            entity.Property(e => e.UnitPrice).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.BuyingGroup)
                .WithMany(p => p.SpecialDeals)
                .HasForeignKey(d => d.BuyingGroupId)
                .HasConstraintName("FK_Sales_SpecialDeals_BuyingGroupID_Sales_BuyingGroups");

            entity.HasOne(d => d.CustomerCategory)
                .WithMany(p => p.SpecialDeals)
                .HasForeignKey(d => d.CustomerCategoryId)
                .HasConstraintName("FK_Sales_SpecialDeals_CustomerCategoryID_Sales_CustomerCategories");

            entity.HasOne(d => d.Customer)
                .WithMany(p => p.SpecialDeals)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("FK_Sales_SpecialDeals_CustomerID_Sales_Customers");

            entity.HasOne(d => d.LastEditedByNavigation)
                .WithMany(p => p.SpecialDeals)
                .HasForeignKey(d => d.LastEditedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Sales_SpecialDeals_Application_People");

            entity.HasOne(d => d.StockGroup)
                .WithMany(p => p.SpecialDeals)
                .HasForeignKey(d => d.StockGroupId)
                .HasConstraintName("FK_Sales_SpecialDeals_StockGroupID_Warehouse_StockGroups");

            entity.HasOne(d => d.StockItem)
                .WithMany(p => p.SpecialDeals)
                .HasForeignKey(d => d.StockItemId)
                .HasConstraintName("FK_Sales_SpecialDeals_StockItemID_Warehouse_StockItems");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SpecialDeal> entity);
    }
}
