// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using wwi.hr.EF;


namespace wwi.hr.EF.Configurations
{
    public partial class VehicleTemperatureConfiguration : IEntityTypeConfiguration<VehicleTemperature>
    {
        public void Configure(EntityTypeBuilder<VehicleTemperature> entity)
        {
            entity.HasKey(e => e.VehicleTemperatureId)
                .HasName("PK_Warehouse_VehicleTemperatures")
                .IsClustered(false);

            entity.ToTable("VehicleTemperatures", "Warehouse");

            entity.HasAnnotation("SqlServer:MemoryOptimized", true);

            entity.Property(e => e.VehicleTemperatureId).HasColumnName("VehicleTemperatureID");

            entity.Property(e => e.FullSensorData)
                .HasMaxLength(1000)
                .UseCollation("Latin1_General_CI_AS");

            entity.Property(e => e.Temperature).HasColumnType("decimal(10, 2)");

            entity.Property(e => e.VehicleRegistration)
                .IsRequired()
                .HasMaxLength(20)
                .UseCollation("Latin1_General_CI_AS");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VehicleTemperature> entity);
    }
}
