services:
    rabbitmq:
        container_name: "rabbitmq-task-practice"
        image: rabbitmq:3.11.15-management
        # environment:
        #     - RABBITMQ_DEFAULT_USER=myuser
        #     - RABBITMQ_DEFAULT_PASS=mypassword
        ports:
            - '5672:5672' # AMQP protocol port
            - '15672:15672' # HTTP management UI
    elk:
        container_name: "elk-task-practice"
        image: sebp/elk:8.7.1
        ports:
            - '5044:5044'
            - '5601:5601'
            - '9200:9200'
            - '9300:9300'
            - '9600:9600'