// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using chores.bl.ef;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace chores.bl.ef.Configurations
{
    public partial class ChoreConfiguration : IEntityTypeConfiguration<Chore>
    {
        public void Configure(EntityTypeBuilder<Chore> entity)
        {
            entity.ToTable("chores");

            entity.HasIndex(e => e.Id, "IX_chores_Id")
                .IsUnique();

            entity.Property(e => e.Name).IsRequired();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Chore> entity);
    }
}
