// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using wwi.bl.EF;

namespace wwi.bl.EF.Configurations
{
    public partial class PurchaseOrderConfiguration : IEntityTypeConfiguration<PurchaseOrder>
    {
        public void Configure(EntityTypeBuilder<PurchaseOrder> entity)
        {
            entity.ToTable("PurchaseOrders", "Purchasing");

            entity.HasIndex(e => e.ContactPersonID, "FK_Purchasing_PurchaseOrders_ContactPersonID");

            entity.HasIndex(e => e.DeliveryMethodID, "FK_Purchasing_PurchaseOrders_DeliveryMethodID");

            entity.HasIndex(e => e.SupplierID, "FK_Purchasing_PurchaseOrders_SupplierID");

            entity.Property(e => e.PurchaseOrderID).HasDefaultValueSql("(NEXT VALUE FOR [Sequences].[PurchaseOrderID])");

            entity.Property(e => e.ExpectedDeliveryDate).HasColumnType("date");

            entity.Property(e => e.LastEditedWhen).HasDefaultValueSql("(sysdatetime())");

            entity.Property(e => e.OrderDate).HasColumnType("date");

            entity.Property(e => e.SupplierReference).HasMaxLength(20);

            entity.HasOne(d => d.ContactPerson)
                .WithMany(p => p.PurchaseOrderContactPeople)
                .HasForeignKey(d => d.ContactPersonID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Purchasing_PurchaseOrders_ContactPersonID_Application_People");

            entity.HasOne(d => d.DeliveryMethod)
                .WithMany(p => p.PurchaseOrders)
                .HasForeignKey(d => d.DeliveryMethodID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Purchasing_PurchaseOrders_DeliveryMethodID_Application_DeliveryMethods");

            entity.HasOne(d => d.LastEditedByNavigation)
                .WithMany(p => p.PurchaseOrderLastEditedByNavigations)
                .HasForeignKey(d => d.LastEditedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Purchasing_PurchaseOrders_Application_People");

            entity.HasOne(d => d.Supplier)
                .WithMany(p => p.PurchaseOrders)
                .HasForeignKey(d => d.SupplierID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Purchasing_PurchaseOrders_SupplierID_Purchasing_Suppliers");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PurchaseOrder> entity);
    }
}
