// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;
using wwi.hr.EF;


namespace wwi.hr.EF.Configurations
{
    public partial class BuyingGroupConfiguration : IEntityTypeConfiguration<BuyingGroup>
    {
        public void Configure(EntityTypeBuilder<BuyingGroup> entity)
        {
            entity.ToTable("BuyingGroups", "Sales");

            entity.HasIndex(e => e.BuyingGroupName, "UQ_Sales_BuyingGroups_BuyingGroupName")
                .IsUnique();

            entity.Property(e => e.BuyingGroupId)
                .HasColumnName("BuyingGroupID")
                .HasDefaultValueSql("(NEXT VALUE FOR [Sequences].[BuyingGroupID])");

            entity.Property(e => e.BuyingGroupName)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.LastEditedByNavigation)
                .WithMany(p => p.BuyingGroups)
                .HasForeignKey(d => d.LastEditedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Sales_BuyingGroups_Application_People");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BuyingGroup> entity);
    }
}
