// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using wwi.bl.EF;

namespace wwi.bl.EF.Configurations
{
    public partial class ColdRoomTemperatureConfiguration : IEntityTypeConfiguration<ColdRoomTemperature>
    {
        public void Configure(EntityTypeBuilder<ColdRoomTemperature> entity)
        {
            entity.HasKey(e => e.ColdRoomTemperatureId)
                .HasName("PK_Warehouse_ColdRoomTemperatures")
                .IsClustered(false);

            entity.ToTable("ColdRoomTemperatures", "Warehouse");

            entity.IsMemoryOptimized()
                .ToTable(tb => tb.IsTemporal(ttb =>
    {
        ttb.UseHistoryTable("ColdRoomTemperatures_Archive", "Warehouse");
        ttb
            .HasPeriodStart("ValidFrom")
            .HasColumnName("ValidFrom");
        ttb
            .HasPeriodEnd("ValidTo")
            .HasColumnName("ValidTo");
    }
));

            entity.HasIndex(e => e.ColdRoomSensorNumber, "IX_Warehouse_ColdRoomTemperatures_ColdRoomSensorNumber");

            entity.Property(e => e.ColdRoomTemperatureId).HasColumnName("ColdRoomTemperatureID");

            entity.Property(e => e.Temperature).HasColumnType("decimal(10, 2)");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ColdRoomTemperature> entity);
    }
}
