// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using wwi.bl.EF;

namespace wwi.bl.EF.Configurations
{
    public partial class OrderLineConfiguration : IEntityTypeConfiguration<OrderLine>
    {
        public void Configure(EntityTypeBuilder<OrderLine> entity)
        {
            entity.ToTable("OrderLines", "Sales");

            entity.HasIndex(e => e.OrderID, "FK_Sales_OrderLines_OrderID");

            entity.HasIndex(e => e.PackageTypeID, "FK_Sales_OrderLines_PackageTypeID");

            entity.HasIndex(e => e.StockItemID, "IX_Sales_OrderLines_AllocatedStockItems");

            entity.HasIndex(e => new { e.PickingCompletedWhen, e.OrderID, e.OrderLineID }, "IX_Sales_OrderLines_Perf_20160301_01");

            entity.HasIndex(e => new { e.StockItemID, e.PickingCompletedWhen }, "IX_Sales_OrderLines_Perf_20160301_02");

            entity.Property(e => e.OrderLineID).HasDefaultValueSql("(NEXT VALUE FOR [Sequences].[OrderLineID])");

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(100);

            entity.Property(e => e.LastEditedWhen).HasDefaultValueSql("(sysdatetime())");

            entity.Property(e => e.TaxRate).HasColumnType("decimal(18, 3)");

            entity.Property(e => e.UnitPrice).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.LastEditedByNavigation)
                .WithMany(p => p.OrderLines)
                .HasForeignKey(d => d.LastEditedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Sales_OrderLines_Application_People");

            entity.HasOne(d => d.Order)
                .WithMany(p => p.OrderLines)
                .HasForeignKey(d => d.OrderID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Sales_OrderLines_OrderID_Sales_Orders");

            entity.HasOne(d => d.PackageType)
                .WithMany(p => p.OrderLines)
                .HasForeignKey(d => d.PackageTypeID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Sales_OrderLines_PackageTypeID_Warehouse_PackageTypes");

            entity.HasOne(d => d.StockItem)
                .WithMany(p => p.OrderLines)
                .HasForeignKey(d => d.StockItemID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Sales_OrderLines_StockItemID_Warehouse_StockItems");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<OrderLine> entity);
    }
}
