// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using wwi.bl.EF;

namespace wwi.bl.EF.Configurations
{
    public partial class OrderConfiguration : IEntityTypeConfiguration<Order>
    {
        public void Configure(EntityTypeBuilder<Order> entity)
        {
            entity.ToTable("Orders", "Sales");

            entity.HasIndex(e => e.ContactPersonID, "FK_Sales_Orders_ContactPersonID");

            entity.HasIndex(e => e.CustomerID, "FK_Sales_Orders_CustomerID");

            entity.HasIndex(e => e.PickedByPersonID, "FK_Sales_Orders_PickedByPersonID");

            entity.HasIndex(e => e.SalespersonPersonID, "FK_Sales_Orders_SalespersonPersonID");

            entity.Property(e => e.OrderID).HasDefaultValueSql("(NEXT VALUE FOR [Sequences].[OrderID])");

            entity.Property(e => e.CustomerPurchaseOrderNumber).HasMaxLength(20);

            entity.Property(e => e.ExpectedDeliveryDate).HasColumnType("date");

            entity.Property(e => e.LastEditedWhen).HasDefaultValueSql("(sysdatetime())");

            entity.Property(e => e.OrderDate).HasColumnType("date");

            entity.HasOne(d => d.BackorderOrder)
                .WithMany(p => p.InverseBackorderOrder)
                .HasForeignKey(d => d.BackorderOrderID)
                .HasConstraintName("FK_Sales_Orders_BackorderOrderID_Sales_Orders");

            entity.HasOne(d => d.ContactPerson)
                .WithMany(p => p.OrderContactPeople)
                .HasForeignKey(d => d.ContactPersonID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Sales_Orders_ContactPersonID_Application_People");

            entity.HasOne(d => d.Customer)
                .WithMany(p => p.Orders)
                .HasForeignKey(d => d.CustomerID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Sales_Orders_CustomerID_Sales_Customers");

            entity.HasOne(d => d.LastEditedByNavigation)
                .WithMany(p => p.OrderLastEditedByNavigations)
                .HasForeignKey(d => d.LastEditedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Sales_Orders_Application_People");

            entity.HasOne(d => d.PickedByPerson)
                .WithMany(p => p.OrderPickedByPeople)
                .HasForeignKey(d => d.PickedByPersonID)
                .HasConstraintName("FK_Sales_Orders_PickedByPersonID_Application_People");

            entity.HasOne(d => d.SalespersonPerson)
                .WithMany(p => p.OrderSalespersonPeople)
                .HasForeignKey(d => d.SalespersonPersonID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Sales_Orders_SalespersonPersonID_Application_People");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Order> entity);
    }
}
