// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using wwi.bl.EF;

namespace wwi.bl.EF.Configurations
{
    public partial class StockItemHoldingConfiguration : IEntityTypeConfiguration<StockItemHolding>
    {
        public void Configure(EntityTypeBuilder<StockItemHolding> entity)
        {
            entity.HasKey(e => e.StockItemId)
                .HasName("PK_Warehouse_StockItemHoldings");

            entity.ToTable("StockItemHoldings", "Warehouse");

            entity.Property(e => e.StockItemId)
                .ValueGeneratedNever()
                .HasColumnName("StockItemID");

            entity.Property(e => e.BinLocation)
                .IsRequired()
                .HasMaxLength(20);

            entity.Property(e => e.LastCostPrice).HasColumnType("decimal(18, 2)");

            entity.Property(e => e.LastEditedWhen).HasDefaultValueSql("(sysdatetime())");

            entity.HasOne(d => d.LastEditedByNavigation)
                .WithMany(p => p.StockItemHoldings)
                .HasForeignKey(d => d.LastEditedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Warehouse_StockItemHoldings_Application_People");

            entity.HasOne(d => d.StockItem)
                .WithOne(p => p.StockItemHolding)
                .HasForeignKey<StockItemHolding>(d => d.StockItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("PKFK_Warehouse_StockItemHoldings_StockItemID_Warehouse_StockItems");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<StockItemHolding> entity);
    }
}
