// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using wwi.bl.EF;

namespace wwi.bl.EF.Configurations
{
    public partial class StockItemStockGroupConfiguration : IEntityTypeConfiguration<StockItemStockGroup>
    {
        public void Configure(EntityTypeBuilder<StockItemStockGroup> entity)
        {
            entity.ToTable("StockItemStockGroups", "Warehouse");

            entity.HasIndex(e => new { e.StockGroupID, e.StockItemID }, "UQ_StockItemStockGroups_StockGroupID_Lookup")
                .IsUnique();

            entity.HasIndex(e => new { e.StockItemID, e.StockGroupID }, "UQ_StockItemStockGroups_StockItemID_Lookup")
                .IsUnique();

            entity.Property(e => e.StockItemStockGroupID).HasDefaultValueSql("(NEXT VALUE FOR [Sequences].[StockItemStockGroupID])");

            entity.Property(e => e.LastEditedWhen).HasDefaultValueSql("(sysdatetime())");

            entity.HasOne(d => d.LastEditedByNavigation)
                .WithMany(p => p.StockItemStockGroups)
                .HasForeignKey(d => d.LastEditedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Warehouse_StockItemStockGroups_Application_People");

            entity.HasOne(d => d.StockGroup)
                .WithMany(p => p.StockItemStockGroups)
                .HasForeignKey(d => d.StockGroupID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Warehouse_StockItemStockGroups_StockGroupID_Warehouse_StockGroups");

            entity.HasOne(d => d.StockItem)
                .WithMany(p => p.StockItemStockGroups)
                .HasForeignKey(d => d.StockItemID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Warehouse_StockItemStockGroups_StockItemID_Warehouse_StockItems");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<StockItemStockGroup> entity);
    }
}
