// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using wwi.bl.EF;

namespace wwi.bl.EF.Configurations
{
    public partial class SupplierTransactionConfiguration : IEntityTypeConfiguration<SupplierTransaction>
    {
        public void Configure(EntityTypeBuilder<SupplierTransaction> entity)
        {
            entity.HasKey(e => e.SupplierTransactionID)
                .HasName("PK_Purchasing_SupplierTransactions")
                .IsClustered(false);

            entity.ToTable("SupplierTransactions", "Purchasing");

            entity.HasIndex(e => e.TransactionDate, "CX_Purchasing_SupplierTransactions")
                .IsClustered();

            entity.HasIndex(e => new { e.TransactionDate, e.PaymentMethodID }, "FK_Purchasing_SupplierTransactions_PaymentMethodID");

            entity.HasIndex(e => new { e.TransactionDate, e.PurchaseOrderID }, "FK_Purchasing_SupplierTransactions_PurchaseOrderID");

            entity.HasIndex(e => new { e.TransactionDate, e.SupplierID }, "FK_Purchasing_SupplierTransactions_SupplierID");

            entity.HasIndex(e => new { e.TransactionDate, e.TransactionTypeID }, "FK_Purchasing_SupplierTransactions_TransactionTypeID");

            entity.HasIndex(e => new { e.TransactionDate, e.IsFinalized }, "IX_Purchasing_SupplierTransactions_IsFinalized");

            entity.Property(e => e.SupplierTransactionID).HasDefaultValueSql("(NEXT VALUE FOR [Sequences].[TransactionID])");

            entity.Property(e => e.AmountExcludingTax).HasColumnType("decimal(18, 2)");

            entity.Property(e => e.FinalizationDate).HasColumnType("date");

            entity.Property(e => e.IsFinalized).HasComputedColumnSql("(case when [FinalizationDate] IS NULL then CONVERT([bit],(0)) else CONVERT([bit],(1)) end)", true);

            entity.Property(e => e.LastEditedWhen).HasDefaultValueSql("(sysdatetime())");

            entity.Property(e => e.OutstandingBalance).HasColumnType("decimal(18, 2)");

            entity.Property(e => e.SupplierInvoiceNumber).HasMaxLength(20);

            entity.Property(e => e.TaxAmount).HasColumnType("decimal(18, 2)");

            entity.Property(e => e.TransactionAmount).HasColumnType("decimal(18, 2)");

            entity.Property(e => e.TransactionDate).HasColumnType("date");

            entity.HasOne(d => d.LastEditedByNavigation)
                .WithMany(p => p.SupplierTransactions)
                .HasForeignKey(d => d.LastEditedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Purchasing_SupplierTransactions_Application_People");

            entity.HasOne(d => d.PaymentMethod)
                .WithMany(p => p.SupplierTransactions)
                .HasForeignKey(d => d.PaymentMethodID)
                .HasConstraintName("FK_Purchasing_SupplierTransactions_PaymentMethodID_Application_PaymentMethods");

            entity.HasOne(d => d.PurchaseOrder)
                .WithMany(p => p.SupplierTransactions)
                .HasForeignKey(d => d.PurchaseOrderID)
                .HasConstraintName("FK_Purchasing_SupplierTransactions_PurchaseOrderID_Purchasing_PurchaseOrders");

            entity.HasOne(d => d.Supplier)
                .WithMany(p => p.SupplierTransactions)
                .HasForeignKey(d => d.SupplierID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Purchasing_SupplierTransactions_SupplierID_Purchasing_Suppliers");

            entity.HasOne(d => d.TransactionType)
                .WithMany(p => p.SupplierTransactions)
                .HasForeignKey(d => d.TransactionTypeID)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Purchasing_SupplierTransactions_TransactionTypeID_Application_TransactionTypes");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SupplierTransaction> entity);
    }
}
