// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using wwi.bl.EF;

namespace wwi.bl.EF.Configurations
{
    public partial class Supplier1Configuration : IEntityTypeConfiguration<Supplier1>
    {
        public void Configure(EntityTypeBuilder<Supplier1> entity)
        {
            entity.HasNoKey();

            entity.ToView("Suppliers", "Website");

            entity.Property(e => e.AlternateContact).HasMaxLength(50);

            entity.Property(e => e.CityName).HasMaxLength(50);

            entity.Property(e => e.DeliveryMethod).HasMaxLength(50);

            entity.Property(e => e.FaxNumber)
                .IsRequired()
                .HasMaxLength(20);

            entity.Property(e => e.PhoneNumber)
                .IsRequired()
                .HasMaxLength(20);

            entity.Property(e => e.PrimaryContact).HasMaxLength(50);

            entity.Property(e => e.SupplierCategoryName).HasMaxLength(50);

            entity.Property(e => e.SupplierId).HasColumnName("SupplierID");

            entity.Property(e => e.SupplierName)
                .IsRequired()
                .HasMaxLength(100);

            entity.Property(e => e.SupplierReference).HasMaxLength(20);

            entity.Property(e => e.WebsiteUrl)
                .IsRequired()
                .HasMaxLength(256)
                .HasColumnName("WebsiteURL");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Supplier1> entity);
    }
}
