// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using wwi.bl.EF;

namespace wwi.bl.EF.Configurations
{
    public partial class SystemParameterConfiguration : IEntityTypeConfiguration<SystemParameter>
    {
        public void Configure(EntityTypeBuilder<SystemParameter> entity)
        {
            entity.ToTable("SystemParameters", "Application");

            entity.HasIndex(e => e.DeliveryCityId, "FK_Application_SystemParameters_DeliveryCityID");

            entity.HasIndex(e => e.PostalCityId, "FK_Application_SystemParameters_PostalCityID");

            entity.Property(e => e.SystemParameterId)
                .HasColumnName("SystemParameterID")
                .HasDefaultValueSql("(NEXT VALUE FOR [Sequences].[SystemParameterID])");

            entity.Property(e => e.ApplicationSettings).IsRequired();

            entity.Property(e => e.DeliveryAddressLine1)
                .IsRequired()
                .HasMaxLength(60);

            entity.Property(e => e.DeliveryAddressLine2).HasMaxLength(60);

            entity.Property(e => e.DeliveryCityId).HasColumnName("DeliveryCityID");

            entity.Property(e => e.DeliveryPostalCode)
                .IsRequired()
                .HasMaxLength(10);

            entity.Property(e => e.LastEditedWhen).HasDefaultValueSql("(sysdatetime())");

            entity.Property(e => e.PostalAddressLine1)
                .IsRequired()
                .HasMaxLength(60);

            entity.Property(e => e.PostalAddressLine2).HasMaxLength(60);

            entity.Property(e => e.PostalCityId).HasColumnName("PostalCityID");

            entity.Property(e => e.PostalPostalCode)
                .IsRequired()
                .HasMaxLength(10);

            entity.HasOne(d => d.DeliveryCity)
                .WithMany(p => p.SystemParameterDeliveryCities)
                .HasForeignKey(d => d.DeliveryCityId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Application_SystemParameters_DeliveryCityID_Application_Cities");

            entity.HasOne(d => d.LastEditedByNavigation)
                .WithMany(p => p.SystemParameters)
                .HasForeignKey(d => d.LastEditedBy)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Application_SystemParameters_Application_People");

            entity.HasOne(d => d.PostalCity)
                .WithMany(p => p.SystemParameterPostalCities)
                .HasForeignKey(d => d.PostalCityId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Application_SystemParameters_PostalCityID_Application_Cities");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SystemParameter> entity);
    }
}
