// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using wwi.bl.EF;

namespace wwi.bl.EF.Configurations
{
    public partial class VehicleTemperature1Configuration : IEntityTypeConfiguration<VehicleTemperature1>
    {
        public void Configure(EntityTypeBuilder<VehicleTemperature1> entity)
        {
            entity.HasNoKey();

            entity.ToView("VehicleTemperatures", "Website");

            entity.Property(e => e.FullSensorData).HasMaxLength(1000);

            entity.Property(e => e.Temperature).HasColumnType("decimal(10, 2)");

            entity.Property(e => e.VehicleRegistration)
                .IsRequired()
                .HasMaxLength(20);

            entity.Property(e => e.VehicleTemperatureId)
                .ValueGeneratedOnAdd()
                .HasColumnName("VehicleTemperatureID");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<VehicleTemperature1> entity);
    }
}
