// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace wwi.bl.EF
{
    public partial class GetMovementUpdatesResult
    {
        [Column("Date Key")]
        public DateTime? DateKey { get; set; }
        [Column("WWI Stock Item Transaction ID")]
        public int WWIStockItemTransactionID { get; set; }
        [Column("WWI Invoice ID")]
        public int? WWIInvoiceID { get; set; }
        [Column("WWI Purchase Order ID")]
        public int? WWIPurchaseOrderID { get; set; }
        public int? Quantity { get; set; }
        [Column("WWI Stock Item ID")]
        public int WWIStockItemID { get; set; }
        [Column("WWI Customer ID")]
        public int? WWICustomerID { get; set; }
        [Column("WWI Supplier ID")]
        public int? WWISupplierID { get; set; }
        [Column("WWI Transaction Type ID")]
        public int WWITransactionTypeID { get; set; }
        [Column("Transaction Occurred When")]
        public DateTime TransactionOccurredWhen { get; set; }
    }
}
