// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace wwi.hr.EF
{
    public partial class GetOrderUpdatesResult
    {
        [Column("Order Date Key")]
        public DateTime? OrderDateKey { get; set; }
        [Column("Picked Date Key")]
        public DateTime? PickedDateKey { get; set; }
        [Column("WWI Order ID")]
        public int WWIOrderID { get; set; }
        [Column("WWI Backorder ID")]
        public int? WWIBackorderID { get; set; }
        public string Description { get; set; }
        public string Package { get; set; }
        public int Quantity { get; set; }
        [Column("Unit Price")]
        public decimal? UnitPrice { get; set; }
        [Column("Tax Rate")]
        public decimal TaxRate { get; set; }
        [Column("Total Excluding Tax")]
        public decimal? TotalExcludingTax { get; set; }
        [Column("Tax Amount")]
        public decimal? TaxAmount { get; set; }
        [Column("Total Including Tax")]
        public decimal? TotalIncludingTax { get; set; }
        [Column("WWI City ID")]
        public int WWICityID { get; set; }
        [Column("WWI Customer ID")]
        public int WWICustomerID { get; set; }
        [Column("WWI Stock Item ID")]
        public int WWIStockItemID { get; set; }
        [Column("WWI Salesperson ID")]
        public int WWISalespersonID { get; set; }
        [Column("WWI Picker ID")]
        public int? WWIPickerID { get; set; }
        [Column("Last Modified When")]
        public DateTime LastModifiedWhen { get; set; }
    }
}
