// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using chores.bl.ef;

#nullable disable

namespace chores.migrations.migrations
{
    [DbContext(typeof(ChoresDbContext))]
    [Migration("20251215104239_CreateChoresCache")]
    partial class CreateChoresCache
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // -------------------------------------------------------
            // chores
            // -------------------------------------------------------
            modelBuilder.Entity("chores.bl.ef.Chore", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex(new[] { "Id" }, "IX_chores_Id")
                    .IsUnique();

                b.ToTable("chores", (string)null);
            });

            // -------------------------------------------------------
            // completed_chores
            // -------------------------------------------------------
            modelBuilder.Entity("chores.bl.ef.CompletedChore", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                b.Property<long>("ChoreId")
                    .HasColumnType("bigint");

                b.Property<long>("Date")
                    .HasColumnType("bigint");

                b.Property<long>("UserId")
                    .HasColumnType("bigint");

                b.HasKey("Id");

                b.HasIndex("ChoreId");

                b.HasIndex(new[] { "Id" }, "IX_completed_chores_Id")
                    .IsUnique();

                b.ToTable("completed_chores", (string)null);
            });

            modelBuilder.Entity("chores.bl.ef.CompletedChore", b =>
            {
                b.HasOne("chores.bl.ef.Chore", "Chore")
                    .WithMany("CompletedChores")
                    .HasForeignKey("ChoreId")
                    .IsRequired();

                b.Navigation("Chore");
            });

            modelBuilder.Entity("chores.bl.ef.Chore", b =>
            {
                b.Navigation("CompletedChores");
            });

            // -------------------------------------------------------
            // chores_cache
            // -------------------------------------------------------
            modelBuilder.Entity("chores_cache", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(449)
                    .HasColumnType("nvarchar(449)");

                b.Property<byte[]>("Value")
                    .HasColumnType("varbinary(max)");

                b.Property<DateTimeOffset>("ExpiresAtTime")
                    .HasColumnType("datetimeoffset");

                b.Property<long?>("SlidingExpirationInSeconds")
                    .HasColumnType("bigint");

                b.Property<DateTimeOffset?>("AbsoluteExpiration")
                    .HasColumnType("datetimeoffset");

                b.HasKey("Id");

                b.ToTable("chores_cache", (string)null);
            });
#pragma warning restore 612, 618
        }
    }
}
