// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using chores.bl.ef;

#nullable disable

namespace chores.migrations.migrations
{
    [DbContext(typeof(ChoresDbContext))]
    [Migration("20251210105650_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("chores.bl.ef.Chore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "IX_chores_Id")
                        .IsUnique();

                    b.ToTable("chores", (string)null);
                });

            modelBuilder.Entity("chores.bl.ef.CompletedChore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChoreId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Date")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChoreId");

                    b.HasIndex(new[] { "Id" }, "IX_completed_chores_Id")
                        .IsUnique();

                    b.ToTable("completed_chores", (string)null);
                });

            modelBuilder.Entity("chores.bl.ef.CompletedChore", b =>
                {
                    b.HasOne("chores.bl.ef.Chore", "Chore")
                        .WithMany("CompletedChores")
                        .HasForeignKey("ChoreId")
                        .IsRequired();

                    b.Navigation("Chore");
                });

            modelBuilder.Entity("chores.bl.ef.Chore", b =>
                {
                    b.Navigation("CompletedChores");
                });
#pragma warning restore 612, 618
        }
    }
}
