# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: dotnet

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  AZURE_WEBAPP_NAME: edum-api
  AZURE_WEBAPP_PACKAGE_PATH: '.publish'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: build, publish and test
      run: |
        dotnet restore
        dotnet build -c Release --no-restore
        dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}' --no-build
        dotnet test --no-build --verbosity normal
    
    - name: deploy to Azure
      uses: azure/azure-webapps-deploy@v3
      with:
        app-name: ${{env.AZURE_WEBAPP_NAME}}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
